### ISSUE TITLE
zcatalog roll-up file contains duplicate targetid

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#13]
When attempting to load the redshift database from the zcatalog-mini.fits file, the unique targetid constraint is violated.

**Comment by sbailey** [comment]
Are the duplicates possibly -1?  What are their DESI_TARGET bits?  i.e. are they normal targets that somehow got replicated, or are they maybe something like unassigned fibers?

**Comment by weaverba137** [comment]
Checking now...

**Comment by weaverba137** [comment]
Well, I can already say that the targetid errors are present in the zbest files, so this isn't a problem with creating the roll-up file.

**Comment by weaverba137** [comment]
There are 15 targets that have `TARGETID == -1`.  All of these objects have `DESI_TARGET == BGS_TARGET == MWS_TARGET == 0`.  I'm also checking for other sorts of duplicates.

**Comment by weaverba137** [comment]
I compared the total number of targets in the zcatalog file to the number of *unique* `TARGETID`s.  Those numbers are 44180 *versus* 44166.  Since -1 would be one of the unique numbers, there are 44165 unique `TARGETID`s that are not -1.  Since there are 15 targets with `TARGETID == -1`, `44165 + 15 = 44180`.  So there can't be any duplicates that *don't* have `TARGETID == -1`.

**Comment by weaverba137** [comment]
PS, in other news, except for this problem, I have successfully made a complete, successful run-through of the minitest notebook using the test-master stack.

**Comment by sbailey** [comment]
The TARGETID=-1 trace all the way back to fiberassign.  Looking at the minitest fiberassign output, some (but not all) of those are from the broken and stuck positioners that aren't assigned to any target.  The remainder will need some more digging, but likely are also due to positioners that couldn't be assigned due to no simulated targets or sky covering them.

For now, please add a filter to the DB loading to ignore any entries with TARGETID=-1.  We can then decide upstream whether we want to do something different with these cases (e.g. to avoid the confusion of some fibers of some exposures going "missing" in the DB, vs. being there in a way that is clear that they are unassigned to any target).

Note: qa-fiberassign incorrectly says no broken or stuck fibers; that is a bug in qa-fiberassign.

**Comment by weaverba137** [comment]
OK, I'll take care of filtering those.  Can you create an issue for qa-fiberassign?

**Comment by sbailey** [comment]
qa-fiberassign: see desihub/fiberassign#132
