### ISSUE TITLE
Include notebook outputs?

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#16]
Before I submit a PR for the 18.6 minitest notebook, I had a question.  When submitting a PR involving a notebook, it might be easier to clear all of the outputs first, making it easier to see changes to the code in the cells, rather  than have the diff full of changes to the output.  Is this something worth doing?

**Comment by sbailey** [comment]
Good question.

In this case, let's keep the outputs in the saved notebook to make it easier to use it as a read-only reference of what was done, without having to re-run the entire notebook.  I agree that this makes it difficult to evaluate diffs, but the usefulness of the fully populated reference notebook outweighs that in my opinion.  i.e. if you want to compare two notebooks without their outputs, it is easier to remove the unwanted outputs than it is to put them back (3 hours and 1500 CPU hours later...)

Other options to consider in the future:
* https://github.com/jupyter/nbdime is supposed to make notebook diffs easier to work with, but I've never used it myself
* We could save a static snapshot of the notebook (html) in the reference run output directory itself, and then clear the outputs for keeping in git.  This would be best if it exporting to html could be automated as the final cell of the notebook, rather than requiring the human to remember to export it.
* It doesn't help with merge conflicts, but for just the purposes of comparison one can always strip the outputs from notebooks in two branches and then compare by hand.  

Related: I would also keep the outputs in the tutorial notebooks for the same reason, though stripping them from the inspector notebook makes sense because the dynamic bokeh/javascript viewer doesn't render in a read-only view on github anyway.

**Comment by weaverba137** [comment]
OK, sounds good.
